infra-services:
  aks_cluster_name: aks-dev-swedencentral
  allow_long_names: true
  applications_destination_repo: https://dev.azure.com/ITGix/Azure%20Landing%20Zones/_git/adp-apps-client
  applications_template_repo: https://github.com/itgix/adp-k8s-templ-argoappsdemo.git
  applications_template_repo_branch: v1.2.3
  azure_devops_org: ITGix
  azure_devops_project: Azure Landing Zones
  azure_subscription_id: f7f8b016-64ca-4d42-afad-de91b2eae685
  backstage_enabled: false
  cluster_name: aks-dev-swedencentral
  dns_main_domain: contoso.internal
  dns_private_zone: contoso.internal
  dns_provider: azure-private-dns
  eks_cluster_name: aks-dev-swedencentral
  dns_client_id: "d8014456-d918-47d1-b5e9-7af74cac5903"
  dns_resource_group: rg-network-dev-swedencentral
  adp_agent_enabled: false
  enable_alloy: true
  enable_cert_manager: true
  enable_falco: true
  enable_gatekeeper: false
  enable_fluent_bit: true
  enable_kyverno: false
  enable_kyverno_policies: false
  enable_traefik: true
  enable_loki: true
  enable_prometheus_stack: true
  enable_tempo: true
  enable_trivy_operator: true
  eso_client_id: "18adee09-fbe3-4328-baef-2752ad5aab03"
  azure_tenant_id: "35e55793-1d03-4bb1-99a3-4888c2cda0e0"
  environment: dev
  gitops_destination_repo: https://dev.azure.com/ITGix/Azure%20Landing%20Zones/_git/adp-argocd-client
  gitops_template_repo: https://github.com/itgix/adp-k8s-templ-argoinfrasvcs.git
  gitops_template_repo_branch: v1.2.17
  project_name: contosoadp
  region: swedencentral
  resource_group: rg-managed-dev-swedencentral
